apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-deny-ingress
spec:
  namespaceSelector: "has(kubernetes.io/metadata.name) && kubernetes.io/metadata.name not in {'kube-system', 'calico-system'}"
  types:
    - Ingress
  ingress:
    - action: Allow
      source:
        selector: "projectcalico.org/created-by == 'calico-kube-controllers'"
    - action: Deny