# namespaces-pods-services.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-c
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: ns-a
  labels:
    app: pod-a
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: ns-b
  labels:
    app: pod-b
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  namespace: ns-c
  labels:
    app: pod-c
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: ns-a
spec:
  selector:
    app: pod-a
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: ns-b
spec:
  selector:
    app: pod-b
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-c
  namespace: ns-c
spec:
  selector:
    app: pod-c
  ports:
    - port: 80
      targetPort: 80